- name: Adding new users
  ansible.builtin.user:
    name: '{{ item.user }}'
    state: present
    comment: '{{ item.desc }}'
    group: '{{ item.grupo }}'
  tags: create_users

  loop:
    - { user: 'splinter', desc: 'mestre', grupo: 'familia' }
    - { user: 'donatelo', desc: 'tartaruga ninja roxo', grupo: 'familia' }