---
 - name: Create folders and users
   hosts: debian
   become: yes
   gather_facts: no 
   tasks:
    - name: Adding new users
      ansible.builtin.user:
         name: '{{ item.user }}'
         state: present
         comment: '{{ item.desc }}'
         group: '{{ item.grupo }}'
      tags: create_users

      loop:
        - { user: 'raquel', desc: 'minha namorada', grupo: 'familia' }
        - { user: 'lucas', desc: 'sobrinho', grupo: 'familia' }

    - name: Creating folders your respectives users
      ansible.builtin.file:
        path: '{{ item.diretorio }}'
        owner: '{{ item.user }}'
        group: '{{ item.grupo }}'
        mode: '0755'
        state: directory
      loop:
        - { user: 'raquel', desc: 'minha namorada', grupo: 'familia', diretorio: '/home/raquel/teste1' }
        - { user: 'lucas', desc: 'sobrinho', grupo: 'familia', diretorio: '/home/lucas/teste2' }
...