---

- name: Create folders and users
  hosts: debian
  become: yes
  gather_facts: no 
  tasks:
   - include_tasks: add_user3.yml
   - name: Creating folders your respectives users
     ansible.builtin.file:
        path: '{{ item.diretorio }}'
        owner: '{{ item.user }}'
        group: '{{ item.grupo }}'
        mode: '0755'
        state: directory
     loop:
        - {  user: 'splinter', grupo: 'familia', diretorio: '/home/splinter/teste1' }
        - {  user: 'splinter', grupo: 'familia', diretorio: '/home/donatelo/teste2' }
...