---
#Author: Andre de Araujo
#Description: define variable for apache2
#YML name: playbook_p_final.yml
#Contact: andredearaujo2007@hotmail.com
#Ansible_Version: 2.10.8
#Last Date: June 2024


# vars file for apache

site_folder: "/var/www/dede_local"
site_url: "www.dede.local"
site_domain: "dede.local"
log_prefix: "dede-local"
php_version: "7.3"