---

- name: Configuration SSH
  hosts: debian
  become: yes
  gather_facts: no
  tasks:

    - name: Changing port ssh 22 to 2404
      ansible.builtin.replace:
        dest: /etc/ssh/sshd_config
        regexp: 'Port 22'
        replace: 'Port 2404'
      notify: restart ssh
      tags: ssh

  handlers:
    - name: restart ssh
      service:
        name: ssh
        state: restarted

...