---
#Author: Andre de Araujo
#Description: include files to executing playblooks
#YML name: playbook_p_final.yml
#Contact: andredearaujo2007@hotmail.com
#Ansible_Version: 2.10.8
#Create in: June 2024
#Last update: 13/06/2024

- name: "Instala o Apache em distro derivadas do Rocky Linux"
  
  yum:
    name: 
      - httpd
      - openssl
      - tar
    state: latest
 
  notify:
    - enablehttpd

- name: "Criar Dir Vhost Rocky Linux"
  file:
    path: "/etc/httpd/vhost.d"
    state: directory
 
- name: "Cria virtual host com as configuracoes do site - Rocky Linux"
  template:
    src: templates/site.conf
    dest: /etc/httpd/vhost.d/{{ log_prefix }}.conf
 
  notify:
    - addHostFile
    - addInHttpdFile
    - RestartHttpd
    - InstallWordPress
    - SetPermissionWP-CentOS