---
- name: Ansible ec2 lauch
  hosts: localhost
  connection: local
  gather_facts: false
  tags: provisioning
  roles:
    
     - aws_ec2
  vars_prompt:
    - name: aws_profile
      prompt: "What is your AWS profile for authentication?"
      private: false
    - name: count
      prompt: How many instance do you want to create?
      private: false
...
