---
- name: Instalacao Pacotes AWS
  hosts: aws_ec2
  gather_facts: false
  become: true
  vars:
    ansible_user: ubuntu  # Ou 'ec2-user' dependendo da AMI da AWS
    ansible_ssh_private_key_file: "~/.aws/kubernetes.pem"
    k8s_version: "v1.30" # Defina a versão desejada do Kubernetes aqui
  roles:
    
     - kubernetes
  
...
#Evite colocar connection local, senao ele nao vai conectar ao cloud se tiver tira