---
  
  - hosts: debian
    become: yes

# This an example about Combine list variables
    vars:
      list1:
      - apple
      - banana
      - fig
      
      list2:
      - peach
      - plum
      - pear
    
      #Combining dictionary variables
      dict1:
        name: Leeroy Jekins
        age: 25
        occupation: Austronaut
      
      dict2:
        location: Galway
        country: Ireland
        postcode: H71 1234

    tasks:
      - name: Combine list1 and list2 into a merged_list var
        ansible.builtin.set_fact:
            merged_list: "{{ list1 + list2 }}"
            
# Show the result this combination
      - name: Show the result of combination
        debug:
          msg: The combination is "{{ merged_list }}"

#Combining dictionary variables
      - name: Combine dict1 and dict2 into a merged_dict var
        ansible.builtin.set_fact:
          merged_dict: "{{ dict1 | ansible.builtin.combine(dict2) }}"

      - name: Show the resulting dictionary variables
        debug:
          msg: The combination is {{ merged_dict }}