---
# handlers file for kubernetes
- name: Reiniciar o containerd
  ansible.builtin.systemd:
      name: containerd
      state: restarted
      enabled: true

- name: Habilitar o servico kubelet
  ansible.builtin.systemd:
    name: kubelet
    state: started
    enabled: true 