---
# Author: Andre de Araujo
# Description: Instalation Database for LAMP and configuration
#YML name: projeto_p_final.yml
#Contact: andredearaujo2007@gmail.com
#Ansible_Version: 2.10.8
#Ano: Junho 2024


# tasks file for mysql
- name: Install Mariadb Server - Rocky Linux
  
  yum:
    name: 
      - mariadb-server
      - python-mysqlclient-doc.x86_64
      - python3-PyMySQL.noarch
      - python3-mysqlclient.x86_64
    state: present
  when: (ansible_facts['os_family'] == "Rocky")

- name: Install Mariadb Server - Debian
  apt:
    update_cache: yes
    name: 
      - mariadb-server
      - python3-mysqldb
      - python3-pymysql
    state: present
  when: (ansible_facts['os_family'] == "Debian")

- name: Start Maria Db
  service:
      name: mariadb
      state: started
      enabled: true

- name: Criando um banco de dados para ser utilizado pelo WordPress - Debian
  
  mysql_db:
    login_unix_socket: "/var/run/mysqld/mysqld.sock"
    name: "{{ db_wp_name }}"
    state: present
  when: (ansible_facts['os_family'] == "Debian")

- name: Criando um banco de dados para ser utilizado pelo WordPress - Rocky
   
  mysql_db:
    login_unix_socket: "/var/lib/mysql/mysql.sock"
    name: "{{ db_wp_name }}"
    state: present
  when: (ansible_facts['os_family'] == "Rocky")

- name: Criando um usuario com senha, todos banco de dados previlegiados - Debian
  
  mysql_user:
    login_unix_socket: "/var/run/mysqld/mysqld.sock"
    name: "{{ db_wp_name }}"
    password: "{{ db_wp_password }}"
    priv: "*.*:ALL,GRANT"
    state: present
  when: (ansible_facts['os_family'] == "Debian")


- name: Criando um usuario com senha, todos banco de dados previlegiados - Rocky
  mysql_user:
    login_unix_socket: "/var/lib/mysql/mysql.sock"
    name: "{{ db_wp_name }}"
    password: "{{ db_wp_password }}"
    priv: "{{ db_wp_name }}.*:ALL,GRANT"
    state: present
  when: (ansible_facts['os_family'] == "Rocky")  

- name: Removes all anonymous user accounts - Debian
  mysql_user:
    login_unix_socket: "/var/run/mysqld/mysqld.sock"
    name: ''
    host: localhost
    state: absent
  when: (ansible_facts['os_family'] == "Debian")  

- name: Removes all anonymous user accounts - Rocky Linux
  mysql_user:
    login_unix_socket: "/var/lib/mysql/mysql.sock"
    name: ''
    host: localhost
    state: absent
  when: (ansible_facts['os_family'] == "Rocky")  