---
# Author: Andre de Araujo
# Description: Instalation Database for LAMP and configuration
#YML name: projeto_p_final.yml
#Contact: andredearaujo2007@gmail.com
#Ansible_Version: 2.10.8
#Ano: Junho 2024
#last modified 02/07/2025 (mm/dd/yyyy)

# tasks file for mysql
- name: Install Mariadb Server - Debian
  import_tasks: debian.yml

- name: Install Mariadb Server - Rocky Linux
  import_tasks: rocky.yml

- name: Create Backup All Databases
  import_tasks: backup.yml
  when: backup_enabled | default(false) | bool