- name: Obter IP privado principal da maquina
  ansible.builtin.set_fact:
    private_ip: "{{ ansible_default_ipv4.address }}"

- name: Executar o kubeadm init
  ansible.builtin.command: >
    kubeadm init 
    --pod-network-cidr=10.10.0.0/16 
    --apiserver-advertise-address={{ private_ip }}
  register: kubeadm_output
  changed_when: "'Your Kubernetes control-plane has initialized successfully!' in kubeadm_output.stdout"
