#Tasks Install Debian packages to install Kubeadm, Kubelet and Kubectl on AWS
#Developed by Andre de Araujo
#Created: 22/07/2026
#Last Modified:

#Update repository packages debian
- name: APT | Update cache
  ansible.builtin.apt:
      update_cache: yes
  
#Upgrade the packages that out of date     
#- name: APT | Update System
 # ansible.builtin.apt:
 #     name: "*"
 #     state: latest
  
#Remove packages that will not more longer
- name: APT | Remove packages no longer required
  ansible.builtin.apt:
    autoremove: true 