

- name: Read contents /var/log/kubernetes/kubeadm_join_command.log and trow in Workers Instances
  ansible.builtin.slurp: #This module it will use remote src to read and execute workes instances
    src: /var/log/kubernetes/kubeadm_join_command.log
  delegate_to: "{{ groups['_kubernetes_instance_1'][0] }}" #Here I'm poiting where from I need to read the content" "In this case the file is other instance calls Control-plane"
  
  register: app_config #Here I created a temporaly variable to save the information"
  
  tags:
    - read_log
  
- name: Show the join command pasted into the Worker
  ansible.builtin.debug:
    msg: "Pasted command ready to execute: {{ app_config.content | b64decode | regex_replace('\\\\\\n\\s*', ' ') | regex_replace('\\n', ' ') | trim }}"
    
    
- name: Execute kubeadm join on Worker
  ansible.builtin.command:
    cmd: "{{ app_config.content | b64decode | regex_replace('\\\\\\n\\s*', ' ') | regex_replace('\\n', ' ') | trim }}"
  when: inventory_hostname in (groups['_kubernetes_instance_2'] + groups['_kubernetes_instance_3'])