---
# tasks file for aws_ec2
  
- name: Criando Instancias
  amazon.aws.ec2_instance:
    profile: "{{ aws_profile }}"
    count: "{{ count }}"
    region: "{{ region }}"
    key_name: "{{ key_name }}"
    security_group: "{{ security_group }}"
    instance_type: "{{ instance_type }}"
    #instance_name: "{{ instance_name }}"
    image_id: "{{ image_id }}"
    instance_initiated_shutdown_behavior: stop
    #termination_protection: yes (This option is a protection destroy VMs unduly )
    wait: true
    wait_timeout: 30

    network:
      assign_public_ip: yes
      
    tags:
      Name: "{{ tag_name }}"  
      Env: "{{ env }}"
      vpc_subnet_id:  "{{ vpc_subnet_id }}"
  register: ec2

- name: Configuring security group for the instance
  amazon.aws.ec2_group:
      name: "{{ security_group }}"
      description: sg giropops
      vpc_id: "{{ vpc_subnet_id }}" 
      profile: "{{ profile }}"
      region: "{{ region }}"
      rules:
        - proto: tcp
          from_port: 22
          to_port: 22
          cidr_ip: 0.0.0.0/0
          rule_desc: SSH
      rules_egress:
        - proto: all
          cidr_ip: 0.0.0.0/0
  register: basic_firewall
