---
# vars file for aws_ec2
profile:        "andre_cli"
region:         "eu-west-2"
key_name:       "ec2"
security_group: "launch-wizard-1"
instance_type:  "t2.small"
instance_name:  "test-ec2-instance"
image_id:       "ami-0f9535ac605dc21d5" 
vpc_subnet_id:  "vpc-05f61ca3183b9b4e4"
tag_name:       "test_ec2"
env:            "STG"
group:          "webserver"
#count: 1
...       
