---
#Author: Andre de Araujo
#Description: Playbook specific for debian PHP
#YML name: playbook_p_final.yml
#Contact: andredearaujo2007@hotmail.com
#Ansible_Version: 2.10.8
#Last Date: June 2024

- name: "Install PHP in Debian" 
  tags: php
  become: yes
  ansible.builtin.apt:
    update_cache: yes
    cache_valid_time: 3600
    name:
      - php7.4
      - php7.4-fpm
      - php7.4-cli
      - php7.4-common
      - php7.4-curl
      - php7.4-mbstring
      - php7.4-mysql
      - php7.4-xml
      - php7.4-gd
      - php7.4-exif
    state: latest
  
