---
#Author: Andre de Araujo
#Description: Playbook specific for rocky PHP
#YML name: playbook_p_final.yml
#Contact: andredearaujo2007@hotmail.com
#Ansible_Version: 2.10.8
#Last Date: June 2024

- name: Enable EPEL Repository on Rocky Linux
  yum:
    name: epel-release
    state: latest

- name: Enable yum-utils
  shell:
    cmd: "yum-config-manager  --enable remi"

- name: "Install PHP in Rocky Linux"
  yum:
    name:
      - php
      - php-mysqlnd
      - php-cli
    state: present
  notify:
   - ReiniciaHttpd
  