---

  - name: Ansible Conditional bool Creating a new file
    hosts: localhost
    vars:
      file: false
    tasks:
      - name: Creating a 'file' in case is true
        ansible.builtin.copy:
          src: /home/ansible/curso_ansible/playbooks/prompt2_var.yml
          dest: /home/ansible/prompt2_var.yml
          owner: ansible
          group: ansible
          mode: '0644'
        when: file | bool
      
      - name: File is false
        ansible.builtin.debug:
          msg: "File will not create"
        when: not file
     
...