---
# This example is a playbook in case exist file it will change for another folder, otherwise it will create a new file and move to other folder
# Date: 21/10/2024
# Finish: 23/10/2024
# Update: 03/11/2024
# Onwer: Andre de Araujo

- name: File exists or not
  hosts: localhost
  gather_facts: no
  tasks:
    - block:
        - name: Verify if the files exist
          ansible.builtin.stat:
            path: "{{ item.dir }}"
          with_items:
            - { dir: '/tmp/teste.txt' }
            - { dir: '/tmp/teste1.txt' }
            - { dir: '/tmp/teste2.txt' }
          register: files
               
        - name: Display if files already exist
          ansible.builtin.debug:
            msg: "!!! FILE {{ item.invocation.module_args.path }} ALREADY EXISTS !!!"
          loop: "{{ files.results }}"
          when: item.stat.exists | default(false)

        - name: Create files that don't exist
          ansible.builtin.file:
            path: "{{ item.invocation.module_args.path }}"
            state: touch
          loop: "{{ files.results }}"
          when: not item.stat.exists | default(true)

      always:
      - name: Move files to /tmp if they didn't exist initially
        ansible.builtin.command: "mv {{ item.invocation.module_args.path }} /tmp"
        loop: "{{ files.results }}"
        when: not item.stat.exists | default(true)
