---
- name: Ansible Stat
  hosts: localhost
  tasks:
   - name: SISOP | Verificando se o arquivo existe
     ansible.builtin.stat: 
      path: /tmp/loop.yml
     register: file

   - debug:
       msg: "File found"
     when: file.stat.exists

   - debug:
       msg: "File not found"
     when: file.stat.exists == false

   - name: Verificar se o proprietario da pasta foi mudado
     ansible.builtin.debug:
       msg: "Ownership has changed"
     when: file.stat.pw_name != 'ansible'

...