---
- name: Sequence with_sequence
  hosts: debian
  become: yes
  tasks:
    - name: USER | Add User
      ansible.builtin.user:
        name: "{{ item }}"
        state: present
        groups: "familia"
      with_sequence: start=0 end=9 format=user%x
 ...