---
- name: Ansible Handlers
  hosts: debian
  become: yes
  tasks:
    - name: NGINX | Listener
      ansible.builtin.replace:
        dest: /etc/nginx/sites-enabled/default
        regexp: 'listen 80 default_server;'
        replace: 'listen {{ ansible_default_ipv4.address }}:80 default_server; '
      notify: restart nginx
  
  handlers:
    - name: restart nginx
      service:
        name: nginx
        state: restarted
        enabled: yes 

...