---
- name: Launch EC2 Instance
  hosts: localhost
  connection: local
  gather_facts: no

  tasks:
    - name: Launch EC2 Instance
      amazon.aws.ec2_instance:
        profile: "andre_cli"
        count: 1
        region: "eu-west-2"
        key_name: "ec2"
        security_group: default
        instance_type: "t2.micro"
        image_id: "ami-0dfe0f1abee59c78d"
        wait: true
    