---

- name: Gather and display specif facts
  hosts: localhost
  gather_facts: yes # você nao precisa declarar pois por default ele já pega o gather_facts
  tasks:
    - name: Display the IP address
      debug:
        var: ansible_facts['default_ipv4']['address']
...