---
-  hosts: localhost
   vars:
     students:
       - Alice
       - Mark
       - Peter

# This example a need to show only one item that is in array example name Peter
   tasks:
        - name: Ansible Array Usage Example
          debug:
           msg: "{{ students[2] }}"

...