---
  - hosts: debian
    become: yes


    tasks:
              
      - name: A list which have another list as item
        debug:
          msg: current value is {{ item }}
        with_items:
            - Tiger
            - [Eagle, Falcon, Monkey, Lion]

      - name: Here we are providing a list which have items containing multiple values
        debug:
          msg: "current first value is {{ item.first }} and  second value is {{ item.second }}"
        with_items:
            - { first: lemon, second: carrot }
            - { first: cow, second: goat }