---
  - hosts: centos
    become: yes

    tasks:

      - name: checking the file existance before creation
        shell: "ls -l /tmp/Sample/file*"
        register: var_output
        ignore_errors: yes

      - name: Here print the output
        debug:
          var: var_output.stdout_lines

      - name: Create a directory call sample
        file:
          path: /tmp/Sample
          state: directory

      - name: create file with diferent user ownership and permission
        file:
          path: "/tmp/Sample/{{ item.name }}"
          state: touch
          modification_time: preserve
          access_time: preserve
          owner: "{{ item.username }}"
          mode: "{{ item.permission }}"
        with_items:
             - { name: file1, username: dex02, permission: '0644'  }
             
            
      - name: checking the file's existance after creation
        shell: "ls -l /tmp/Sample/file*"
        register: var_output1  

      - name: output
        debug:
          var: var_output1.stdout_lines 
    
    