---

- name: Ansible Prompt | Creating user on Linux
  hosts: localhost
  vars_prompt:
    - name: username
      prompt: What is your username?
      private: false
    
    - name: password
      prompt: What is your password?
      private: true # Opcional por default e true
      encrypt: "md5_crypt"
      confirm: yes
      salt_size: 7
    
    - name: shell
      prompt: What is your shell?
      private: false

  tasks:
    - name: Print a message
      ansible.builtin.debug:
        msg: 'Usuario {{ username }} | Password: {{ password }} | Shell: {{ shell }}'
    
    - name: USER | Add user
      ansible.builtin.user:
        name: "{{ username }}"
        comment: "User create by Ansible"
        shell: "{{ shell }}"
        home: "/home/{{ username }}"
        password: "{{ password }}"

...