---

- name: Update System
  hosts: samba
  gather_facts: True 
  become: yes
  
  tasks:

    - name: APT | Update repositories
      ansible.builtin.apt:
        update_cache: yes
      when: ansible_distribution == "Debian" or ansible_hostname == "srv-debian"
     
    - name: APT | Update System Packages
      ansible.builtin.apt:
        name: "*"
        state: latest
      when: ansible_distribution == "Debian" or ansible_hostname == "srv-debian"

    - name: APT | Remove packages no longer required
      ansible.builtin.apt:
        autoremove: true 
    
    - name: Install Samba application
      ansible.builtin.apt:
        pkg:
          - samba
          - cifs-utils
          
    - name: Configure sharing vm-backup in Samba
      ansible.builting.ini_file:
        path /etc/samba/smb.conf
        
          
    
...